# .readthedocs.yml

version: 2

sphinx:
  configuration: docs/conf.py

formats:
   - pdf

build:
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs