[tool.poetry]
name = "perceptivo"
version = "0.0.1"
description = ""
authors = ["sneakers-the-rat <JLSaunders987@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.9"
pip = "^21.1.3"
auto-pi-lot = { git = "https://github.com/wehr-lab/autopilot.git", branch = "dev" }
pyzmq = "^22.3.0"
scikit-learn = "^1.0.1"
matplotlib = "^3.4.3"
PySide6 = {version = "^6.1.2", optional=true}
pyqtgraph = {version = "^0.12", optional=true}
JACK-Client = {version="^0.5.3", optional=true}
sphinx = {version = "^4.2", optional=true}
furo = {version = "^2021", optional=true}
myst-parser = {version ="^0.15", optional=true}
sphinxcontrib-bibtex = {version="^2.4.1", optional=true}
numpy = "^1.21"
importlib-metadata = {version="^4.10", python="~3.7"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
patient = 'perceptivo.patient:main'
clinician = 'perceptivo.clinician:main'

[tool.poetry.extras]
docs = ["sphinx", "furo", "myst-parser", "sphinxcontrib-bibtex"]
patient = ["JACK-Client"]
clinician = ["PySide6", "pyqtgraph"]

[[tool.poetry.source]]
name = "piwheels.org"
url = "https://www.piwheels.org/simple"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
