[tool.poetry]
name = "perceptivo"
version = "0.0.1"
description = ""
authors = ["sneakers-the-rat <JLSaunders987@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
sphinx = {version = "^4.2", optional=true}
furo = {version = "^2021", optional=true}
myst-parser = {version ="^0.15", optional=true}
pip = "^21.1.3"
PySide6 = "^6.1.2"
PsychoPy = "^2021.2.0"
auto-pi-lot = "^0.4"
pyqtgraph = "^0.12"
pyzmq = "^22.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
patient = 'perceptivo.patient:main'
clinician = 'perceptivo.clinician:main'

[tool.poetry.extras]
docs = ["sphinx", "furo", "myst-parser"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
