[tool.poetry]
name = "perceptivo"
version = "0.0.1"
description = ""
authors = ["sneakers-the-rat <JLSaunders987@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
sphinx = {version = "^3.5.4", optional=true}
furo = {version = "^2021.4.11-beta.34", optional=true}
myst-parser = {version ="^0.15.0", optional=true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.extras]
docs = ["sphinx", "furo", "myst-parser"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
